apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-backup-pv
  namespace: kube-system
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etcd_backup
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: etcd-backup-pv
  resources:
    requests:
      storage: 8Gi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: kube-system
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: bitnami/etcd
              securityContext:
                runAsUser: 0
              command: ["/bin/sh", "-c"]
              args:
                - |
                  etcdctl snapshot save /etcd_backup/etcd-snapshot-$(date +%Y%m%d_%H%M%S).db \
                  --cert=/etc/ssl/etcd/ssl/admin-${NODE_NAME}.pem \
                  --key=/etc/ssl/etcd/ssl/admin-${NODE_NAME}-key.pem
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: ETCDCTL_ENDPOINTS
                  value: "https://127.0.0.1:2379"
                - name: ETCDCTL_API
                  value: "3"
                - name: ETCDCTL_CACERT
                  value: "/etc/ssl/etcd/ssl/ca.pem"
              volumeMounts:
                - name: etcd-certs
                  mountPath: /etc/ssl/etcd/ssl
                  readOnly: true
                - name: backup
                  mountPath: /etcd_backup
              resources:
                limits:
                  cpu: "250m"
                  memory: "500Mi"
            - name: backup-purge
              image: busybox:1.31.1
              command: ["/bin/sh", "-c"]
              args:
                - find /etcd_backup -type f -name '*.db' -mtime +1 -exec rm -f {} \;
              volumeMounts:
                - name: backup
                  mountPath: /etcd_backup
              resources:
                limits:
                  cpu: "250m"
                  memory: "500Mi"
          restartPolicy: OnFailure
          dnsPolicy: ClusterFirst
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          volumes:
            - name: etcd-certs
              hostPath:
                path: /etc/ssl/etcd/ssl
            - name: backup
              persistentVolumeClaim:
                claimName: etcd-backup
  schedule: "@hourly"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false